# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: ["pleasework"]
  pull_request:
    branches: ["pleasework"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: pleasework
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "sbt"
      - name: install sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt
      - name: compile
        run: sbt compile
        working-directory: starrealms

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: pleasework
          fetch-depth: 0
      - name: install sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt
      - name: build project and export coverage
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN }}
        run: |
          export CI_BRANCH="${GITHUB_REF#refs/heads/}"
          sbt clean coverage test coverageReport coveralls
        working-directory: starrealms
