name: Scala CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch the full history
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "sbt"
      - name: install sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt
      - name: compile
        run: sbt compile
      #- name: compile
      #  run: sbt --allow-empty compile

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch the full history
      - name: install sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt
      - name: build project and export coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          export CI_BRANCH="${GITHUB_REF#refs/heads/}"
          sbt clean coverage test coverageReport coveralls
