name: Scala CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

      - name: Display current branch
        run: 'echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"'
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main # Changed to branch name
          fetch-depth: 0


      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch the full history

      - name: compile
        run: sbt compile
        working-directory: starrealms

      #- name: compile
      #  run: sbt compile
      - name: compile
        run: sbt --allow-empty compile


      - name: Display current branch
        run: 'echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"'
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main # Changed to branch name
          fetch-depth: 0

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch the full history

        working-directory: starrealms
      - name: Debug GITHUB_REF and GITHUB_SHA
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "Extracted CI_BRANCH: ${GITHUB_REF#refs/heads/}"

