name: Scala CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Ensure proper branch or commit is fetched

      # Step 2: Set HEAD to a branch
      - name: Set HEAD to a branch
        run: |
          git symbolic-ref HEAD refs/heads/main || git checkout -b main

      # Step 3: Debug Git State (Optional for troubleshooting)
      - name: Debug Git State
        run: |
          git status
          git branch -a
          git log --oneline -5

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk

      # Step 5: Run build and tests
      - name: Build and test
        run: sbt clean compile test

      # Step 6: Coveralls (Ensure proper Git state)
      - name: Coveralls
        run: sbt coveralls
