name: Scala CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write # notwendig für Coveralls Reporting

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      CARDS_CSV_PATH: starrealms/src/main/resources/FullCardItinerary.csv

    steps:
      - name: Checkout with full Git history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "sbt"

      - name: Install sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Ensure FullCardItinerary.csv exists
        run: |
          mkdir -p starrealms/src/main/resources
          echo "Set,Qty,Name,Text,CardType,Faction,Cost,Defense,Role,Notes" > starrealms/src/main/resources/FullCardItinerary.csv

      - name: Debug .git and build.sbt
        working-directory: starrealms
        run: |
          echo "PWD: $(pwd)"
          ls -la
          if [ -d .git ]; then ls -la .git; else echo ".git directory not found here"; fi
          test -f build.sbt && echo "build.sbt found" || echo "build.sbt missing"

      - name: Run tests and report coverage to Coveralls
        working-directory: starrealms
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          sbt clean coverage test coverageReport coveralls

      - name: Normalize scoverage.xml paths
        run: |
          REPO_ROOT="$(pwd)/"
          sed -i'' "s|$REPO_ROOT||g" target/scala-2.13/scoverage-report/scoverage.xml
