name: Scala CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write # notwendig für Coveralls Reporting

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with full Git history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "sbt"

      - name: Install sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Build, test, and publish coverage
        working-directory: starrealms
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          sbt clean coverage test coverageReport coveralls
